# ==========================================
# CONEXÃO COM O BANCO DE DADOS (SUPABASE)
# ==========================================

# 1. Usamos a string exata que você copiou do painel (porta 5432)
# 2. Adicionamos o "?tcpKeepAlive=true" no final para estabilizar a rede
spring.datasource.url=jdbc:postgresql://db.shrjfcfenwmpzxnwjxgc.supabase.co:5432/postgres?tcpKeepAlive=true

# O usuário correto para essa URL direta é apenas "postgres"
spring.datasource.username=postgres

# A senha do seu banco de dados
spring.datasource.password=h7yF93gnH{Ji

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true